version: '2'

volumes:
  teamcity_server_data: {}
  teamcity_server_logs: {}

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    env_file: .env
    restart: always

  teamcity-ruby-agent:
     build: ./agents/ruby
     env_file: .env
     restart: always

  teamcity-node-agent:
    build: ./agents/node
    env_file: .env
    restart: always